# Generated by Django 4.0.2 on 2022-04-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0003_remove_question_user_answer_reply_profile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.IntegerField(default=15, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='islam',
            field=models.CharField(choices=[('A', 'Islam By Birth'), ('B', 'Convert')], max_length=100, null=True),
        ),
    ]
