# Generated by Django 4.0.2 on 2022-04-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0005_answer_like_alter_answer_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
