# Generated by Django 4.0.2 on 2022-04-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0006_alter_answer_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=models.CharField(max_length=1000),
        ),
    ]
