# Generated by Django 4.0.2 on 2022-05-03 21:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ask', '0008_remove_answer_title_question_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='dislike',
            field=models.ManyToManyField(blank=True, null=True, related_name='dislike', to=settings.AUTH_USER_MODEL),
        ),
    ]
