# Generated by Django 4.0.2 on 2022-05-14 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0009_answer_dislike'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
    ]
