# Generated by Django 4.0.2 on 2022-05-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0011_question_support_alter_answer_dislike_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='dislike',
            field=models.ManyToManyField(blank=True, related_name='dislike', to='ask.Profile'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like', to='ask.Profile'),
        ),
        migrations.AlterField(
            model_name='question',
            name='Support',
            field=models.ManyToManyField(blank=True, related_name='support', to='ask.Profile'),
        ),
    ]
