# Generated by Django 4.0.2 on 2022-05-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0012_alter_answer_dislike_alter_answer_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='follow',
            field=models.ManyToManyField(related_name='follows', to='ask.Profile'),
        ),
    ]
