# Generated by Django 4.0.2 on 2022-05-20 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0013_alter_profile_follow'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='color',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
