# Generated by Django 4.0.2 on 2022-05-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0014_answer_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Views',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
