# Generated by Django 4.0.2 on 2022-06-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0017_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Key', models.CharField(max_length=1000)),
                ('mode', models.CharField(choices=[('Light', 'Light'), ('Dark', 'Dark')], default='Light', max_length=10)),
            ],
        ),
    ]
