# Generated by Django 4.0.2 on 2022-04-25 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ask', '0008_remove_answer_title_question_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Hadith', 'Hadith'), ('Fiqh', 'Fiqh'), ('Taoheed', 'Taoheed'), ('Language', 'Language'), ('General', 'General')], max_length=30)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('head', models.CharField(max_length=30)),
                ('Image', models.ImageField(upload_to='images/')),
                ('body', models.TextField()),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puser', to='ask.profile')),
            ],
            options={
                'ordering': ['Date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(auto_now_add=True, null=True)),
                ('name', models.CharField(max_length=25)),
                ('body', models.TextField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='forum.post')),
                ('reply', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replys', to='forum.comment')),
            ],
            options={
                'ordering': ['Date'],
            },
        ),
    ]
