# Generated by Django 4.0.2 on 2022-05-14 22:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0010_alter_question_options'),
        ('forum', '0003_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AlterField(
            model_name='comment',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 23, 9, 47, 599429)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 14, 23, 9, 47, 591964)),
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('member', models.ManyToManyField(null=True, related_name='group', to='ask.Profile')),
            ],
        ),
    ]
