# Generated by Django 4.0.2 on 2022-05-19 14:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0006_alter_comment_date_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 15, 1, 38, 127313)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 15, 1, 38, 120365)),
        ),
    ]
