# Generated by Django 4.0.2 on 2022-05-19 14:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ask', '0013_alter_profile_follow'),
        ('forum', '0007_alter_comment_date_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 15, 3, 8, 357292)),
        ),
        migrations.AlterField(
            model_name='group',
            name='member',
            field=models.ManyToManyField(related_name='group', to='ask.Profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 19, 15, 3, 8, 350014)),
        ),
    ]
