# Generated by Django 4.0.2 on 2022-05-30 11:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0014_alter_comment_date_alter_post_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 12, 48, 51, 884607)),
        ),
        migrations.AlterField(
            model_name='post',
            name='Date',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 30, 12, 48, 51, 878401)),
        ),
    ]
